In [1]:
import tensorflow as tf
from keras.datasets import mnist  

In [2]:
(x_train, y_train),(x_test, y_test) = mnist.load_data()

In [3]:
import numpy as np
np.set_printoptions(linewidth=200)
import matplotlib.pyplot as plt
plt.imshow(x_train[0])
print(y_train[0])
print(x_train[0])
# it's a 5

5
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 182 247 241   0 

In [4]:
#normalizing the images
x_train  = x_train / 255.0
x_test = x_test / 255.0

In [5]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(512, activation = tf.nn.relu),
                                    tf.keras.layers.Dense(10, activation = tf.nn.softmax)])

In [6]:
class myCallBack(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs ={} ):
        if (logs.get('accuracy') >= 0.99):
            self.model.stop_training = True
            
callbacks = myCallBack()

In [7]:
model.compile(optimizer = "adam",
             loss = 'sparse_categorical_crossentropy',
             metrics = ['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs = 10, callbacks = [callbacks])

Epoch 1/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2012 - accuracy: 0.9414
Epoch 2/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0810 - accuracy: 0.9751
Epoch 3/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0527 - accuracy: 0.9831
Epoch 4/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0353 - accuracy: 0.9887
Epoch 5/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0290 - accuracy: 0.9905


In [9]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.0631 - accuracy: 0.9813


[0.06308846175670624, 0.9812999963760376]